export const LOAD_FAVORITES = 'LOAD_FAVORITES'
export const LOAD_FAVORITES__SUCCESS = 'LOAD_FAVORITES__SUCCESS' 
export const LOAD_FAVORITES__FAILURE = 'LOAD_FAVORITES__FAILURE'

export const ADD_FAVORITES = 'ADD_FAVORITES'
export const ADD_FAVORITES__SUCCESS = 'ADD_FAVORITES__SUCCESS' 
export const ADD_FAVORITES__FAILURE = 'ADD_FAVORITES__FAILURE'

export const REMOVE_FAVORITES = 'REMOVE_FAVORITES'
export const REMOVE_FAVORITES__SUCCESS = 'REMOVE_FAVORITES__SUCCESS' 
export const REMOVE_FAVORITES__FAILURE = 'REMOVE_FAVORITES__FAILURE'