export const LOAD_BASKET = 'LOAD_BASKET'
export const LOAD_BASKET__SUCCESS = 'LOAD_BASKET__SUCCESS' 
export const LOAD_BASKET__FAILURE = 'LOAD_BASKET__FAILURE'

export const ADD_BASKET = 'ADD_BASKET'
export const ADD_BASKET__SUCCESS = 'ADD_BASKET__SUCCESS' 
export const ADD_BASKET__FAILURE = 'ADD_BASKET__FAILURE'

export const REMOVE_BASKET = 'REMOVE_BASKET'
export const REMOVE_BASKET__SUCCESS = 'REMOVE_BASKET__SUCCESS' 
export const REMOVE_BASKET__FAILURE = 'REMOVE_BASKET__FAILURE'


export const DELETE_ALL_BASKET = 'DELETE_ALL_BASKET'
export const DELETE_ALL_BASKET__SUCCESS = 'DELETE_ALL_BASKET__SUCCESS'
export const DELETE_ALL_BASKET__FAILURE = 'DELETE_ALL_BASKET__FAILURE'