export const LOAD_ORDER = 'LOAD_ORDER'
export const LOAD_ORDER__SUCCESS = 'LOAD_ORDER__SUCCESS' 
export const LOAD_ORDER__FAILURE = 'LOAD_ORDER__FAILURE'

export const ADD_ORDER = 'ADD_ORDER'
export const ADD_ORDER__SUCCESS = 'ADD_ORDER__SUCCESS' 
export const ADD_ORDER__FAILURE = 'ADD_ORDER__FAILURE'

export const REMOVE_ORDER = 'REMOVE_ORDER'
export const REMOVE_ORDER__SUCCESS = 'REMOVE_ORDER__SUCCESS' 
export const REMOVE_ORDER__FAILURE = 'REMOVE_ORDER__FAILURE'